package:
  name: selina
  version: '0.1'

source:
  path: ../

requirements:
  build:
    - python=3.9.7
  run:
    - datatable=0.11.1
    - pytorch=1.10.0
    - python=3.9.7
    - pandas=1.3.4
    - numpy=1.22.3
    - tqdm=4.62.3
    - h5py=3.4.0
    - pytables=3.6.1
    - scipy=1.6.3
    - r-deldir=1.0_2 
    - r-seurat=4.0.3
    - r-hdf5r=1.3.4
    - r-data.table=1.14.0
    - r-optparse=1.7.1
    - imbalanced-learn=0.8.1 
    - r-devtools=2.4.3
    - bioconductor-deseq2=1.34.0

about:
    license: GPL-3.0
    home: https://github.com/pfren1998/SELINA

